apiVersion: skaffold/v2beta29
kind: Config
deploy:
  kubectl:
    manifests:
      - infra/k8s/*
      - infra/k8s-dev/*
build:
  local:
    push: false
  artifacts:
    - image: tranducmille/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .